## Joint model with lambda = 0.01

python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Augmentation/Joint0.01Model__Seed1/grayscale/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.0004 -lr 0.001 -scheduler_step 20 -end2end -augmentation_type='grayscale'
python3 src/jointmodelexp.py cub Joint --seed 2 -ckpt 1 -log_dir Joint-models-log/Augmentation/Joint-models-log/Joint0.01Model__Seed2/grayscale/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.0004 -lr 0.001 -scheduler_step 20 -end2end -augmentation_type='grayscale'
python3 src/jointmodelexp.py cub Joint --seed 3 -ckpt 1 -log_dir Joint-models-log/Augmentation/Joint-models-log/Joint0.01Model_Seed3/grayscale/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end -augmentation_type='grayscale'
python3 src/CUB/inference.py -model_dirs Joint-models-log/Augmentation/Joint0.01Model__Seed1/grayscale/outputs/best_model_1.pth Joint-models-log/Augmentation/Joint0.01Model__Seed2/grayscale/outputs/best_model_2.pth oint-models-log/Joint0.01Model_Seed3/grayscale/outputs/ -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -feature_group_results -log_dir Joint-models-log/Augmentation/Joint0.01Model/grayscale/outputs

python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Joint0.01Model__Seed1/rotation/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.0004 -lr 0.001 -scheduler_step 20 -end2end -augmentation_type='rotation'
python3 src/jointmodelexp.py cub Joint --seed 2 -ckpt 1 -log_dir Joint-models-log/Joint0.01Model__Seed2/rotation/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.0004 -lr 0.001 -scheduler_step 20 -end2end -augmentation_type='rotation'
python3 src/jointmodelexp.py cub Joint --seed 3 -ckpt 1 -log_dir Joint-models-log/Joint0.01Model_Seed3/rotation/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end -augmentation_type='rotation'
# python3 src/CUB/inference.py -model_dirs Joint-models-log/Joint0.01Model__Seed1/rotation/outputs/best_model_1.pth Joint-models-log/Joint0.01Model__Seed2/rotation/outputs/best_model_2.pth oint-models-log/Joint0.01Model_Seed3/rotation/outputs/ -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -feature_group_results -log_dir Joint-models-log/Joint0.01Model/rotation/outputs

python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Joint0.01Model__Seed1/center_crop/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.0004 -lr 0.001 -scheduler_step 20 -end2end -augmentation_type='center_crop'
python3 src/jointmodelexp.py cub Joint --seed 2 -ckpt 1 -log_dir Joint-models-log/Joint0.01Model__Seed2/center_crop/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.0004 -lr 0.001 -scheduler_step 20 -end2end -augmentation_type='center_crop'
python3 src/jointmodelexp.py cub Joint --seed 3 -ckpt 1 -log_dir Joint-models-log/Joint0.01Model_Seed3/center_crop/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end -augmentation_type='center_crop'
# python3 src/CUB/inference.py -model_dirs Joint-models-log/Joint0.01Model__Seed1/center_crop/outputs/best_model_1.pth Joint-models-log/Joint0.01Model__Seed2/center_crop/outputs/best_model_2.pth oint-models-log/Joint0.01Model_Seed3/center_crop/outputs/ -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -feature_group_results -log_dir Joint-models-log/Joint0.01Model/center_crop/outputs