# # THis is the main model we are using.
# python3 src/inference.py -model_dirs Joint-models-log/Joint0.001Model_Seed1/outputs/best_model_1.pth Joint-models-log/Joint0.001Model_Seed2/outputs/best_model_2.pth Joint-models-log/Joint0.001Model_Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Joint0.001Model/outputs/no-adv
# This works but just for 2 models with 0.01
# python3 src/inference.py -model_dirs Joint-models-log/Joint0.01Model__Seed1/outputs/best_model_1.pth Joint-models-log/Joint0.01Model__Seed2/outputs/best_model_2.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Joint0.01Model/outputs/no-adv

###### For following 2 to work, we need to have Joint-models-log/Joint0.01Model__Seed3/outputs/best_model_3.pth, Joint-models-log/Joint0.1Model__Seed1/outputs/best_model_1.pth Joint-models-log/Joint0.1Model__Seed2/outputs/best_model_2.pth Joint-models-log/Joint0.1Model__Seed3/outputs/best_model_3.pth which we did not train, 
# python3 src/inference.py -model_dirs Joint-models-log/Joint0.01Model__Seed1/outputs/best_model_1.pth Joint-models-log/Joint0.01Model__Seed2/outputs/best_model_2.pth Joint-models-log/Joint0.01Model__Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Joint0.01Model/outputs/no-adv
# python3 src/inference.py -model_dirs Joint-models-log/Joint0.1Model__Seed1/outputs/best_model_1.pth Joint-models-log/Joint0.1Model__Seed2/outputs/best_model_2.pth Joint-models-log/Joint0.1Model__Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Joint0.1Model/outputs/no-adv

# Now lets report adversarial dataset on the above models
# python3 src/adv-bird-data-eval.py -model_dirs Joint-models-log/Joint0.001Model_Seed1/outputs/best_model_1.pth Joint-models-log/Joint0.001Model_Seed2/outputs/best_model_2.pth Joint-models-log/Joint0.001Model_Seed3/outputs/best_model_3.pth -eval_data test  -use_attr -n_attributes 112  -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Joint-models-log-eval-no_attr/Joint0.1Model/outputs/adv-eval/0.01 -adv_imgs_dir src/datasets/CUB_processed_adversarial_jointmdl_attr_save -perturbed_imgs_dir src/datasets/CUB_processed_adversarial_perturb_jointmdl_attr_save -eps 0.01
# python3 src/adv-bird-data-eval.py -model_dirs Joint-models-log/Joint0.001Model_Seed1/outputs/best_model_1.pth Joint-models-log/Joint0.001Model_Seed2/outputs/best_model_2.pth Joint-models-log/Joint0.001Model_Seed3/outputs/best_model_3.pth -eval_data test  -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Joint-models-log-eval-no_attr/Joint0.1Model/outputs/adv-eval/0.03 -adv_imgs_dir src/datasets/CUB_processed_adversarial_jointmdl_attr_save -perturbed_imgs_dir src/datasets/CUB_processed_adversarial_perturb_jointmdl -eps 0.03
# python3 src/adv-bird-data-eval.py -model_dirs Joint-models-log/Joint0.001Model_Seed1/outputs/best_model_1.pth Joint-models-log/Joint0.001Model_Seed2/outputs/best_model_2.pth Joint-models-log/Joint0.001Model_Seed3/outputs/best_model_3.pth -eval_data test  -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Joint-models-log-eval-no_attr/Joint0.1Model/outputs/adv-eval/0.1 -adv_imgs_dir src/datasets/CUB_processed_adversarial_jointmdl_attr_save -perturbed_imgs_dir src/datasets/CUB_processed_adversarial_perturb_jointmdl -eps 0.1
# python3 src/adv-bird-data-eval.py -model_dirs Joint-models-log/Joint0.001Model_Seed1/outputs/best_model_1.pth Joint-models-log/Joint0.001Model_Seed2/outputs/best_model_2.pth Joint-models-log/Joint0.001Model_Seed3/outputs/best_model_3.pth -eval_data test  -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Joint-models-log-eval-no_attr/Joint0.1Model/outputs/adv-eval/0.3 -adv_imgs_dir src/datasets/CUB_processed_adversarial_jointmdl_attr_save -perturbed_imgs_dir src/datasets/CUB_processed_adversarial_perturb_jointmdl -eps 0.5



### Now lets report for image processing on the above models

# python3 src/inference.py -model_dirs Joint-models-log/Augmentation/grayscale/Joint0.001Model_Seed1/outputs/best_model_1.pth Joint-models-log/Augmentation/grayscale/Joint0.001Model_Seed2/outputs/best_model_2.pth Joint-models-log/Augmentation/grayscale/Joint0.001Model_Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Augmentation/grayscale/Joint0.001Model/outputs/grayscale
# python3 src/inference.py -model_dirs Joint-models-log/Augmentation/rotation/Joint0.001Model_Seed1/outputs/best_model_1.pth Joint-models-log/Augmentation/rotation/Joint0.001Model_Seed2/outputs/best_model_2.pth Joint-models-log/Augmentation/rotation/Joint0.001Model_Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Augmentation/rotation/Joint0.001Model/outputs/rotation
# python3 src/inference.py -model_dirs Joint-models-log/Augmentation/center_crop/Joint0.001Model_Seed1/outputs/best_model_1.pth Joint-models-log/Augmentation/center_crop/Joint0.001Model_Seed2/outputs/best_model_2.pth Joint-models-log/Augmentation/center_crop/Joint0.001Model_Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Augmentation/center_crop/Joint0.001Model/outputs/center_crop
python3 src/inference.py -model_dirs Joint-models-log/Augmentation/custom/Joint0.001Model_Seed1/outputs/best_model_1.pth Joint-models-log/Augmentation/custom/Joint0.001Model_Seed2/outputs/best_model_2.pth Joint-models-log/Augmentation/custom/Joint0.001Model_Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Augmentation/custom/Joint0.001Model/outputs/custom



