# ### Joint Model



# # python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Joint0.001Model_Seed1/outputs/ -e 5 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
# python3 src/inference.py -model_dirs Joint-models-log/Joint0.001Model_Seed1/outputs/best_model_1.pth  -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir  Joint-models-log/Joint0.001Model/outputs
# #### Concept loss weight = 0.001
# python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Joint0.001Model_Seed1/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
python3 src/jointmodelexp.py cub Joint --seed 2 -ckpt 1 -log_dir Joint-models-log/Joint0.001Model_Seed2/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
python3 src/jointmodelexp.py cub Joint --seed 3 -ckpt 1 -log_dir Joint-models-log/Joint0.001Model_Seed3/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
python3 src/inference.py -model_dirs Joint-models-log/Joint0.001Model_Seed1/outputs/best_model_1.pth Joint-models-log/Joint0.001Model_Seed2/outputs/best_model_2.pth Joint-models-log/Joint0.001Model_Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Joint0.001Model/outputs
#### Concept loss weight = 0.01
python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Joint0.01Model__Seed1/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.0004 -lr 0.001 -scheduler_step 20 -end2end
python3 src/jointmodelexp.py cub Joint --seed 2 -ckpt 1 -log_dir Joint-models-log/Joint0.01Model__Seed2/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.0004 -lr 0.001 -scheduler_step 20 -end2end
python3 src/jointmodelexp.py cub Joint --seed 3 -ckpt 1 -log_dir Joint-models-log/Joint0.01Model_Seed3/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
python3 src/inference.py -model_dirs Joint-models-log/Joint0.01Model__Seed1/outputs/best_model_1.pth Joint-models-log/Joint0.01Model__Seed2/outputs/best_model_2.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -feature_group_results -log_dir Joint-models-log/Joint0.01Model/outputs
python3 src/inference.py -model_dirs Joint-models-log/Joint0.001Model_Seed1/outputs/best_model_1.pth Joint-models-log/Joint0.001Model_Seed2/outputs/best_model_2.pth Joint-models-log/Joint0.001Model_Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Joint0.001Model/outputs
python3 src/inference.py -model_dirs Joint-models-log/Joint0.01Model__Seed1/outputs/best_model_1.pth Joint-models-log/Joint0.01Model__Seed2/outputs/best_model_2.pth Joint-models-log/Joint0.01Model__Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Joint0.01Model/outputs

#### Concept loss weight = 0.01, with Sigmoid
python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Joint0.01SigmoidModel__Seed1/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.0004 -lr 0.001 -scheduler_step 20 -end2end -use_sigmoid
python3 src/jointmodelexp.py cub Joint --seed 2 -ckpt 1 -log_dir Joint-models-log/Joint0.01SigmoidModel__Seed2/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.0004 -lr 0.001 -scheduler_step 20 -end2end -use_sigmoid
python3 src/jointmodelexp.py cub Joint --seed 3 -ckpt 1 -log_dir Joint-models-log/Joint0.01SigmoidModel__Seed3/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.0004 -lr 0.001 -scheduler_step 20 -end2end -use_sigmoid
#### Concept loss weight = 0.1
python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Joint0.1Model__Seed1/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.1 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
python3 src/jointmodelexp.py cub Joint --seed 2 -ckpt 1 -log_dir Joint-models-log/Joint0.1Model__Seed2/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.1 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
python3 src/jointmodelexp.py cub Joint --seed 3 -ckpt 1 -log_dir Joint-models-log/Joint0.1Model__Seed3/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.1 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
python3 src/inference.py -model_dirs Joint-models-log/Joint0.1Model__Seed1/outputs/best_model_1.pth Joint-models-log/Joint0.1Model__Seed2/outputs/best_model_2.pth Joint-models-log/Joint0.1Model__Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Joint-models-log/Joint0.1Model/outputs
#### Concept loss weight = 1
python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Joint-models-log/Joint1Model__Seed1/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 1 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
python3 src/jointmodelexp.py cub Joint --seed 2 -ckpt 1 -log_dir Joint-models-log/Joint1Model__Seed2/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 1 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
python3 src/jointmodelexp.py cub Joint --seed 3 -ckpt 1 -log_dir Joint-models-log/Joint1Model__Seed3/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 1 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
python3 src/inference.py -model_dirs Joint-models-log/Joint1Model__Seed1/outputs/best_model_1.pth Joint-models-log/Joint1Model__Seed2/outputs/best_model_2.pth Joint-models-log/Joint1Model__Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Joint1Model/outputs