### Concept models
# python3 src/experiments.py cub Concept_XtoC --seed 1 -ckpt 1 -log_dir Augmentation/ConceptModel__Seed1/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -bottleneck -augmentation_type='grayscale'
# python3 src/experiments.py cub Concept_XtoC --seed 2 -ckpt 1 -log_dir Augmentation/ConceptModel__Seed2/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -bottleneck -augmentation_type='grayscale'
# python3 src/experiments.py cub Concept_XtoC --seed 3 -ckpt 1 -log_dir Augmentation/ConceptModel__Seed3/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -bottleneck -augmentation_type='grayscale'


# python3 src/experiments.py cub Concept_XtoC --seed 1 -ckpt 1 -log_dir Augmentation/ConceptModel__Seed1/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -bottleneck -augmentation_type='rotation'
# python3 src/experiments.py cub Concept_XtoC --seed 2 -ckpt 1 -log_dir Augmentation/ConceptModel__Seed2/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -bottleneck -augmentation_type='rotation'
# python3 src/experiments.py cub Concept_XtoC --seed 3 -ckpt 1 -log_dir Augmentation/ConceptModel__Seed3/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -bottleneck -augmentation_type='rotation'


# python3 src/experiments.py cub Concept_XtoC --seed 1 -ckpt 1 -log_dir Augmentation/ConceptModel__Seed1/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -bottleneck -augmentation_type='center_crop'
# python3 src/experiments.py cub Concept_XtoC --seed 2 -ckpt 1 -log_dir Augmentation/ConceptModel__Seed2/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -bottleneck -augmentation_type='center_crop'
# python3 src/experiments.py cub Concept_XtoC --seed 3 -ckpt 1 -log_dir Augmentation/ConceptModel__Seed3/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -bottleneck -augmentation_type='center_crop'


# python3 src/experiments.py cub Concept_XtoC --seed 1 -ckpt 1 -log_dir Augmentation/ConceptModel__Seed1/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -bottleneck -augmentation_type='custom'
# python3 src/experiments.py cub Concept_XtoC --seed 2 -ckpt 1 -log_dir Augmentation/ConceptModel__Seed2/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -bottleneck -augmentation_type='custom'
# python3 src/experiments.py cub Concept_XtoC --seed 3 -ckpt 1 -log_dir Augmentation/ConceptModel__Seed3/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -bottleneck -augmentation_type='custom'


# python3 src/generate_new_data.py ExtractConcepts --model_path ConceptModel__Seed1/outputs/best_model_1.pth --data_dir src/datasets/CUB_processed/class_attr_data_10 --out_dir ConceptModel1__PredConcepts
# python3 src/generate_new_data.py ExtractConcepts --model_path ConceptModel__Seed2/outputs/best_model_2.pth --data_dir src/datasets/CUB_processed/class_attr_data_10 --out_dir ConceptModel2__PredConcepts
# python3 src/generate_new_data.py ExtractConcepts --model_path ConceptModel__Seed3/outputs/best_model_3.pth --data_dir src/datasets/CUB_processed/class_attr_data_10 --out_dir ConceptModel3__PredConcepts

# # # # ### Independent Model
# python3 src/experiments.py cub Independent_CtoY --seed 1 -log_dir Augmentation/IndependentModel_WithVal___Seed1/outputs/ -e 10 -optimizer sgd -use_attr -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -scheduler_step 2 -augmentation_type='grayscale'
# python3 src/experiments.py cub Independent_CtoY --seed 2 -log_dir Augmentation/IndependentModel_WithVal___Seed2/outputs/ -e 10 -optimizer sgd -use_attr -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -scheduler_step 2 -augmentation_type='grayscale'
# python3 src/experiments.py cub Independent_CtoY --seed 3 -log_dir Augmentation/IndependentModel_WithVal___Seed3/outputs/ -e 10 -optimizer sgd -use_attr -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -scheduler_step 2 -augmentation_type='grayscale'
# python3 src/inference.py -model_dirs Augmentation/ConceptModel__Seed1/outputs/best_model_1.pth Augmentation/ConceptModel__Seed2/outputs/best_model_2.pth Augmentation/ConceptModel__Seed3/outputs/best_model_3.pth -model_dirs2 Augmentation/IndependentModel_WithVal___Seed1/outputs/best_model_1.pth Augmentation/IndependentModel_WithVal___Seed2/outputs/best_model_2.pth Augmentation/IndependentModel_WithVal___Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -bottleneck -use_sigmoid -log_dir Augmentation/IndependentModel__WithValSigmoid/outputs -augmentation_type='grayscale'

# python3 src/experiments.py cub Independent_CtoY --seed 1 -log_dir Augmentation/IndependentModel_WithVal___Seed1/outputs/ -e 10 -optimizer sgd -use_attr -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -scheduler_step 2 -augmentation_type='rotation'
# python3 src/experiments.py cub Independent_CtoY --seed 2 -log_dir Augmentation/IndependentModel_WithVal___Seed2/outputs/ -e 10 -optimizer sgd -use_attr -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -scheduler_step 2 -augmentation_type='rotation'
# python3 src/experiments.py cub Independent_CtoY --seed 3 -log_dir Augmentation/IndependentModel_WithVal___Seed3/outputs/ -e 10 -optimizer sgd -use_attr -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -scheduler_step 2 -augmentation_type='rotation'
# python3 src/inference.py -model_dirs Augmentation/ConceptModel__Seed1/outputs/best_model_1.pth Augmentation/ConceptModel__Seed2/outputs/best_model_2.pth Augmentation/ConceptModel__Seed3/outputs/best_model_3.pth -model_dirs2 Augmentation/IndependentModel_WithVal___Seed1/outputs/best_model_1.pth Augmentation/IndependentModel_WithVal___Seed2/outputs/best_model_2.pth Augmentation/IndependentModel_WithVal___Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -bottleneck -use_sigmoid -log_dir Augmentation/IndependentModel__WithValSigmoid/outputs -augmentation_type='rotation'


# python3 src/experiments.py cub Independent_CtoY --seed 1 -log_dir Augmentation/IndependentModel_WithVal___Seed1/outputs/ -e 10 -optimizer sgd -use_attr -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -scheduler_step 2 -augmentation_type='center_crop'
# python3 src/experiments.py cub Independent_CtoY --seed 2 -log_dir Augmentation/IndependentModel_WithVal___Seed2/outputs/ -e 10 -optimizer sgd -use_attr -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -scheduler_step 2 -augmentation_type='center_crop'
# python3 src/experiments.py cub Independent_CtoY --seed 3 -log_dir Augmentation/IndependentModel_WithVal___Seed3/outputs/ -e 10 -optimizer sgd -use_attr -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -scheduler_step 2 -augmentation_type='center_crop'
# python3 src/inference.py -model_dirs Augmentation/ConceptModel__Seed1/outputs/best_model_1.pth Augmentation/ConceptModel__Seed2/outputs/best_model_2.pth Augmentation/ConceptModel__Seed3/outputs/best_model_3.pth -model_dirs2 Augmentation/IndependentModel_WithVal___Seed1/outputs/best_model_1.pth Augmentation/IndependentModel_WithVal___Seed2/outputs/best_model_2.pth Augmentation/IndependentModel_WithVal___Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -bottleneck -use_sigmoid -log_dir Augmentation/IndependentModel__WithValSigmoid/outputs -augmentation_type='center_crop'



# python3 src/experiments.py cub Independent_CtoY --seed 1 -log_dir Augmentation/IndependentModel_WithVal___Seed1/outputs/ -e 10 -optimizer sgd -use_attr -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -scheduler_step 2 -augmentation_type='custom'
# python3 src/experiments.py cub Independent_CtoY --seed 2 -log_dir Augmentation/IndependentModel_WithVal___Seed2/outputs/ -e 10 -optimizer sgd -use_attr -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -scheduler_step 2 -augmentation_type='custom'
# python3 src/experiments.py cub Independent_CtoY --seed 3 -log_dir Augmentation/IndependentModel_WithVal___Seed3/outputs/ -e 10 -optimizer sgd -use_attr -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -no_img -b 64 -weight_decay 0.00005 -lr 0.001 -scheduler_step 2 -augmentation_type='custom'
# python3 src/inference.py -model_dirs Augmentation/ConceptModel__Seed1/outputs/best_model_1.pth Augmentation/ConceptModel__Seed2/outputs/best_model_2.pth Augmentation/ConceptModel__Seed3/outputs/best_model_3.pth -model_dirs2 Augmentation/IndependentModel_WithVal___Seed1/outputs/best_model_1.pth Augmentation/IndependentModel_WithVal___Seed2/outputs/best_model_2.pth Augmentation/IndependentModel_WithVal___Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -bottleneck -use_sigmoid -log_dir Augmentation/IndependentModel__WithValSigmoid/outputs -augmentation_type='custom'



# # # ### Sequential Model
# python3 src/experiments.py cub Sequential_CtoY --seed 1 -log_dir SequentialModel_WithVal__Seed1/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -data_dir ConceptModel1__PredConcepts -n_attributes 112 -no_img -b 64 -weight_decay 0.00004 -lr 0.001 -scheduler_step 2
# python3 src/experiments.py cub Sequential_CtoY --seed 2 -log_dir SequentialModel_WithVal__Seed2/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -data_dir ConceptModel2__PredConcepts -n_attributes 112 -no_img -b 64 -weight_decay 0.00004 -lr 0.001 -scheduler_step 2
# python3 src/experiments.py cub Sequential_CtoY --seed 3 -log_dir SequentialModel_WithVal__Seed3/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -data_dir ConceptModel3__PredConcepts -n_attributes 112 -no_img -b 64 -weight_decay 0.00004 -lr 0.001 -scheduler_step 2
# python3 src/inference.py -model_dirs ConceptModel__Seed1/outputs/best_model_1.pth ConceptModel__Seed2/outputs/best_model_2.pth ConceptModel__Seed3/outputs/best_model_3.pth -model_dirs2 SequentialModel_WithVal__Seed1/outputs/best_model_1.pth SequentialModel_WithVal__Seed2/outputs/best_model_2.pth SequentialModel_WithVal__Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -bottleneck -feature_group_results -log_dir SequentialModel__WithVal/outputs

# # # ### Standard Model
# python3 src/experiments.py cub Joint --seed 1 -ckpt 1 -log_dir Joint0Model_Seed1/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -end2end
# python3 src/experiments.py cub Joint --seed 2 -ckpt 1 -log_dir Joint0Model_Seed2/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -end2end
# python3 src/experiments.py cub Joint --seed 3 -ckpt 1 -log_dir Joint0Model_Seed3/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -end2end
# python3 src/inference.py -model_dirs Joint0Model_Seed1/outputs/best_model_1.pth Joint0Model_Seed2/outputs/best_model_2.pth Joint0Model_Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint0Model/outputs

# # # ### Standard Model Linear Probe
# # python3 src/generate_new_data.py ExtractProbeRepresentations --model_path Joint0Model_Seed1/outputs/best_model_1.pth --layer_idx -1 --data_dir CUB_processed/class_attr_data_10 --out_dir Joint0Model_Seed1_ExtractProbeRep
# # python3 src/generate_new_data.py ExtractProbeRepresentations --model_path Joint0Model_Seed2/outputs/best_model_2.pth --layer_idx -1 --data_dir CUB_processed/class_attr_data_10 --out_dir Joint0Model_Seed2_ExtractProbeRep
# # python3 src/generate_new_data.py ExtractProbeRepresentations --model_path Joint0Model_Seed3/outputs/best_model_3.pth --layer_idx -1 --data_dir CUB_processed/class_attr_data_10 --out_dir Joint0Model_Seed3_ExtractProbeRep
# # python3 src/probe.py -data_dir Joint0Model_Seed1_ExtractProbeRep -n_attributes 112 -log_dir Joint0Model_Seed1_LinearProbe/outputs -lr 0.001 -scheduler_step 5 -weight_decay 0.00004
# # python3 src/probe.py -data_dir Joint0Model_Seed2_ExtractProbeRep -n_attributes 112 -log_dir Joint0Model_Seed2_LinearProbe/outputs -lr 0.001 -scheduler_step 5 -weight_decay 0.00004
# # python3 src/probe.py -data_dir Joint0Model_Seed3_ExtractProbeRep -n_attributes 112 -log_dir Joint0Model_Seed3_LinearProbe/outputs -lr 0.001 -scheduler_step 5 -weight_decay 0.00004
# # python3 src/probe.py -data_dirs Joint0Model_Seed1_ExtractProbeRep Joint0Model_Seed2_ExtractProbeRep Joint0Model_Seed3_ExtractProbeRep -log_dir Joint0Model_LinearProbe -eval -model_dirs Joint0Model_Seed1_LinearProbe/outputs/best_model.pth Joint0Model_Seed2_LinearProbe/outputs/best_model.pth Joint0Model_Seed3_LinearProbe/outputs/best_model.pth

# # # ### Standard No Bottleneck Model
# python3 src/experiments.py cub Standard --seed 1 -ckpt 1 -log_dir StandardNoBNModel_Seed1/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -data_dir src/datasets/CUB_processed/class_attr_data_10 -b 64 -weight_decay 0.0004 -lr 0.01 -scheduler_step 2
# python3 src/experiments.py cub Standard --seed 2 -ckpt 1 -log_dir StandardNoBNModel_Seed2/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -data_dir src/datasets/CUB_processed/class_attr_data_10 -b 64 -weight_decay 0.0004 -lr 0.01 -scheduler_step 2
# python3 src/experiments.py cub Standard --seed 3 -ckpt 1 -log_dir StandardNoBNModel_Seed3/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -data_dir src/datasets/CUB_processed/class_attr_data_10 -b 64 -weight_decay 0.0004 -lr 0.01 -scheduler_step 2
# python3 src/inference.py -model_dirs StandardNoBNModel_Seed1/outputs/best_model_1.pth StandardNoBNModel_Seed2/outputs/best_model_2.pth StandardNoBNModel_Seed3/outputs/best_model_3.pth -eval_data test -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir StandardNoBNModel/outputs

# # ### Joint Model
# # #### Concept loss weight = 0.001
# python3 src/experiments.py cub Joint --seed 1 -ckpt 1 -log_dir Joint0.001Model_Seed1/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -end2end
# python3 src/experiments.py cub Joint --seed 2 -ckpt 1 -log_dir Joint0.001Model_Seed2/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -end2end
# python3 src/experiments.py cub Joint --seed 3 -ckpt 1 -log_dir Joint0.001Model_Seed3/outputs/ -e 10 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 2 -end2end
# python3 src/inference.py -model_dirs Joint0.001Model_Seed1/outputs/best_model_1.pth Joint0.001Model_Seed2/outputs/best_model_2.pth Joint0.001Model_Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint0.001Model/outputs





###### This is the main for now


# #### Concept loss weight = 0.001
python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Augmentation/grayscale/Joint0.001Model_Seed1/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end -augmentation_type='grayscale' -device cuda:4
python3 src/jointmodelexp.py cub Joint --seed 2 -ckpt 1 -log_dir Joint-models-log/Augmentation/grayscale/Joint0.001Model_Seed2/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end -augmentation_type='grayscale' -device cuda:4
python3 src/jointmodelexp.py cub Joint --seed 3 -ckpt 1 -log_dir Joint-models-log/Augmentation/grayscale/Joint0.001Model_Seed3/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end -augmentation_type='grayscale' -device cuda:4
python3 src/inference.py -model_dirs Joint-models-log/Augmentation/grayscale/Joint0.001Model_Seed1/outputs/best_model_1.pth Joint-models-log/Augmentation/grayscale/Joint0.001Model_Seed2/outputs/best_model_2.pth Joint-models-log/Augmentation/grayscale/Joint0.001Model_Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Augmentation/grayscale/Joint0.001Model/outputs


python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Augmentation/rotation/Joint0.001Model_Seed1/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end -augmentation_type='rotation' -device cuda:4
python3 src/jointmodelexp.py cub Joint --seed 2 -ckpt 1 -log_dir Joint-models-log/Augmentation/rotation/Joint0.001Model_Seed2/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end -augmentation_type='rotation' -device cuda:4
python3 src/jointmodelexp.py cub Joint --seed 3 -ckpt 1 -log_dir Joint-models-log/Augmentation/rotation/Joint0.001Model_Seed3/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end -augmentation_type='rotation' -device cuda:4
python3 src/inference.py -model_dirs Joint-models-log/Augmentation/rotation/Joint0.001Model_Seed1/outputs/best_model_1.pth Joint-models-log/Augmentation/rotation/Joint0.001Model_Seed2/outputs/best_model_2.pth Joint-models-log/Augmentation/rotation/Joint0.001Model_Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Augmentation/rotation/Joint0.001Model/outputs

python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Augmentation/center_crop/Joint0.001Model_Seed1/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end -augmentation_type='center_crop' -device cuda:4
python3 src/jointmodelexp.py cub Joint --seed 2 -ckpt 1 -log_dir Joint-models-log/Augmentation/center_crop/Joint0.001Model_Seed2/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end -augmentation_type='center_crop' -device cuda:4
python3 src/jointmodelexp.py cub Joint --seed 3 -ckpt 1 -log_dir Joint-models-log/Augmentation/center_crop/Joint0.001Model_Seed3/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end -augmentation_type='center_crop' -device cuda:4
python3 src/inference.py -model_dirs Joint-models-log/Augmentation/center_crop/Joint0.001Model_Seed1/outputs/best_model_1.pth Joint-models-log/Augmentation/center_crop/Joint0.001Model_Seed2/outputs/best_model_2.pth Joint-models-log/Augmentation/center_crop/Joint0.001Model_Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Augmentation/center_crop/Joint0.001Model/outputs

python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Augmentation/custom/Joint0.001Model_Seed1/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end -augmentation_type='custom' -device cuda:4
python3 src/jointmodelexp.py cub Joint --seed 2 -ckpt 1 -log_dir Joint-models-log/Augmentation/custom/Joint0.001Model_Seed2/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end -augmentation_type='custom' -device cuda:4
python3 src/jointmodelexp.py cub Joint --seed 3 -ckpt 1 -log_dir Joint-models-log/Augmentation/custom/Joint0.001Model_Seed3/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.001 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end -augmentation_type='custom' -device cuda:4
python3 src/inference.py -model_dirs Joint-models-log/Augmentation/custom/Joint0.001Model_Seed1/outputs/best_model_1.pth Joint-models-log/Augmentation/custom/Joint0.001Model_Seed2/outputs/best_model_2.pth Joint-models-log/Augmentation/custom/Joint0.001Model_Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Augmentation/custom/Joint0.001Model/outputs

#### Concept loss weight = 0.01
# python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Augmentation/Joint0.01Model__Seed1/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.0004 -lr 0.001 -scheduler_step 20 -end2end  -augmentation_type='grayscale'
# python3 src/jointmodelexp.py cub Joint --seed 2 -ckpt 1 -log_dir Joint-models-log/Augmentation/Joint0.01Model__Seed2/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.0004 -lr 0.001 -scheduler_step 20 -end2end -augmentation_type='grayscale'
# python3 src/jointmodelexp.py cub Joint --seed 3 -ckpt 1 -log_dir Joint-models-log/Augmentation/Joint0.01Model_Seed3/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end -augmentation_type='grayscale'
# python3 src/inference.py -model_dirs Joint-models-log/Augmentation/Joint0.01Model__Seed1/outputs/best_model_1.pth Joint-models-log/Augmentation/Joint0.01Model__Seed2/outputs/best_model_2.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -feature_group_results -log_dir Joint-models-log/Augmentation/Joint0.01Model/outputs
# python3 src/inference.py -model_dirs Joint-models-log/Augmentation/Joint0.01Model__Seed1/outputs/best_model_1.pth Joint-models-log/Augmentation/Joint0.01Model__Seed2/outputs/best_model_2.pth Joint-models-log/Augmentation/Joint0.01Model__Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Augmentation/Joint0.01Model/outputs

# #### Concept loss weight = 0.01, with Sigmoid
# python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Augmentation/Joint0.01SigmoidModel__Seed1/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.0004 -lr 0.001 -scheduler_step 20 -end2end -use_sigmoid
# python3 src/jointmodelexp.py cub Joint --seed 2 -ckpt 1 -log_dir Joint-models-log/Augmentation/Joint0.01SigmoidModel__Seed2/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.0004 -lr 0.001 -scheduler_step 20 -end2end -use_sigmoid
# python3 src/jointmodelexp.py cub Joint --seed 3 -ckpt 1 -log_dir Joint-models-log/Augmentation/Joint0.01SigmoidModel__Seed3/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.01 -normalize_loss -b 64 -weight_decay 0.0004 -lr 0.001 -scheduler_step 20 -end2end -use_sigmoid
# #### Concept loss weight = 0.1
# python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Augmentation/Joint0.1Model__Seed1/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.1 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
# python3 src/jointmodelexp.py cub Joint --seed 2 -ckpt 1 -log_dir Joint-models-log/Augmentation/Joint0.1Model__Seed2/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.1 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
# python3 src/jointmodelexp.py cub Joint --seed 3 -ckpt 1 -log_dir Joint-models-log/Augmentation/Joint0.1Model__Seed3/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 0.1 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
# python3 src/inference.py -model_dirs Joint-models-log/Augmentation/Joint0.1Model__Seed1/outputs/best_model_1.pth Joint-models-log/Augmentation/Joint0.1Model__Seed2/outputs/best_model_2.pth Joint-models-log/Augmentation/Joint0.1Model__Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Augmentation/Joint-models-log/Augmentation/Joint0.1Model/outputs
# #### Concept loss weight = 1
# python3 src/jointmodelexp.py cub Joint --seed 1 -ckpt 1 -log_dir Joint-models-log/Augmentation/Joint-models-log/Augmentation/Joint1Model__Seed1/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 1 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
# python3 src/jointmodelexp.py cub Joint --seed 2 -ckpt 1 -log_dir Joint-models-log/Augmentation/Joint1Model__Seed2/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 1 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
# python3 src/jointmodelexp.py cub Joint --seed 3 -ckpt 1 -log_dir Joint-models-log/Augmentation/Joint1Model__Seed3/outputs/ -e 100 -optimizer sgd -pretrained -use_aux -use_attr -weighted_loss multiple -data_dir src/datasets/CUB_processed/class_attr_data_10 -n_attributes 112 -attr_loss_weight 1 -normalize_loss -b 64 -weight_decay 0.00004 -lr 0.01 -scheduler_step 20 -end2end
# python3 src/inference.py -model_dirs Joint-models-log/Augmentation/Joint1Model__Seed1/outputs/best_model_1.pth Joint-models-log/Augmentation/Joint1Model__Seed2/outputs/best_model_2.pth Joint-models-log/Augmentation/Joint1Model__Seed3/outputs/best_model_3.pth -eval_data test -use_attr -n_attributes 112 -data_dir src/datasets/CUB_processed/class_attr_data_10 -log_dir Joint-models-log/Augmentation/Joint1Model/outputs